eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    status-page-url: https://localhost:${eureka.instance.secure-port}/actuator/info
    health-check-url: https://localhost:${eureka.instance.secure-port}/actuator/health
    home-page-url: https://localhost:${eureka.instance.secure-port}
  client:
    serviceUrl:
      defaultZone: https://localhost:8085/eureka/
#      defaultZone: http://localhost:8085/eureka/
      register-with-eureka: true
      fetch-registry: false
---
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
---
spring:
  cloud:
    bus:
      enabled: true
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
      refresh:
        enabled: true
      env:
        enabled: true
---
springdoc:
  show-actuator: true
---
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
---
spring:
  sleuth:
    sampler:
      probability: 1.0
---
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    metrigs:
      tags:
        application: ${spring.application.name}

---
info:
  application:
    name: ${spring.application.name}
    developer:
      email: fbobylev@sberbank.ru




